### ISSUE TITLE
MYSQL error

### ISSUE THREAD

**Issue by MrBanaan** [lessevv/communitypanel#1]
Beste Wessel, misschien ken je me nog van Habbo, ThiefCreatief, :-Creatief-. Ik krijg steeds errors met de mysql. Kan je misschien een update maken waarin alles vernieuwd is? Of kan je me helpen het op te lossen via mijn host. Add me op skype: ThiefCreatief

**Comment by lessevv** [comment]
Kan je iets specifieker zijn welke errors je krijgt?
